# command line: video_demo.py --video /home/peter/dataset/gist/org/mid2019/roaming_kym_trial1/student4.avi --outdir /home/peter/tmp/bbox_test --save_video

config: graph/config/inference.yaml
device:
- 0
ignore_weights: []
model: graph.gcn_utils.gcn_model.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: PoseTrack
        strategy: spatial
    in_channels: 2
    num_class: 128
outputpath: /home/peter/tmp/bbox_test
print_log: true
save_log: true
save_video: true
use_gpu: true
video: /home/peter/dataset/gist/org/mid2019/roaming_kym_trial1/student4.avi
weights: ./weights/GCN/epoch210_model.pt
work_dir: ./work_dir/tmp
