# command line: /home/peter/workspace/ict2019/video_demo.py --video /home/peter/dataset/gist/org/mid2019/gta_dh_trial_2/trim_ohryong1.avi

config: graph/config/inference.yaml
device:
- 0
ignore_weights: []
model: graph.gcn_utils.gcn_model.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: PoseTrack
        strategy: spatial
    in_channels: 2
    num_class: 128
outputpath: examples/res/
print_log: true
save_log: true
save_video: false
sp: false
use_gpu: true
video: /home/peter/dataset/gist/org/mid2019/gta_dh_trial_2/trim_ohryong1.avi
weights: ./weights/GCN/epoch210_model.pt
work_dir: ./work_dir/tmp
